const UI = {
  English: {
    easy: "Easy", medium: "Medium", hard: "Hard",
    assessment: "Assessment", answered: "answered", generating: "Generating your {tier} questions…",
    gradingEasy: "Grading Easy tier, generating Medium questions…",
    gradingMedium: "Grading Medium tier, generating Hard questions…",
    submitNext: "Submit Tier & Unlock Next", submitResult: "Submit & See Result",
    answerEvery: "Answer every question to continue.",
    terminated: "Assessment terminated",
    violation: "Proctoring detected a rule violation, so the exam was submitted automatically with whatever had been answered so far. This attempt is disqualified from Expert status.",
    somethingWrong: "Something went wrong", backendHint: "Make sure the backend is running and Ollama is available at the configured host.",
    back: "Back to start", stillWorking: "Still working — local models can take time depending on your machine and model.",
    q: "Q", result: "Assessment Result", correct: "correct", points: "pts", tierReview: "tier review",
    noAnswer: "no answer", youPicked: "You picked", correctAnswer: "Correct", expert: "EXPERT", disqualified: "DISQUALIFIED",
    scoreExpert: "You scored {percent}% — that clears the 80% bar. You're certified Expert in {skill}.",
    scoreRetry: "You scored {percent}% — just under the 80% Expert bar. Solid attempt, worth another run.",
    terminatedResult: "This attempt was terminated by proctoring — {reason}. It was auto-submitted and is not eligible for Expert status.",
    tryAgain: "Try another skill"
  },
  Hindi: {
    easy: "आसान", medium: "मध्यम", hard: "कठिन", assessment: "परीक्षा", answered: "उत्तर दिए", generating: "आपके {tier} प्रश्न तैयार किए जा रहे हैं…",
    gradingEasy: "आसान स्तर की जाँच हो रही है, मध्यम प्रश्न तैयार किए जा रहे हैं…", gradingMedium: "मध्यम स्तर की जाँच हो रही है, कठिन प्रश्न तैयार किए जा रहे हैं…",
    submitNext: "स्तर जमा करें और अगला स्तर खोलें", submitResult: "जमा करें और परिणाम देखें", answerEvery: "आगे बढ़ने के लिए हर प्रश्न का उत्तर दें।",
    terminated: "परीक्षा समाप्त कर दी गई", violation: "निगरानी में नियम उल्लंघन पाया गया, इसलिए परीक्षा अपने आप जमा कर दी गई। यह प्रयास विशेषज्ञ दर्जे के लिए मान्य नहीं है।",
    somethingWrong: "कुछ गलत हुआ", backendHint: "सुनिश्चित करें कि बैकएंड और Ollama चल रहे हैं।", back: "शुरुआत पर जाएँ", stillWorking: "अभी काम चल रहा है — स्थानीय मॉडल को कुछ समय लग सकता है।",
    q: "प्रश्न", result: "परीक्षा परिणाम", correct: "सही", points: "अंक", tierReview: "स्तर समीक्षा", noAnswer: "कोई उत्तर नहीं", youPicked: "आपने चुना", correctAnswer: "सही उत्तर", expert: "विशेषज्ञ", disqualified: "अयोग्य",
    scoreExpert: "आपका स्कोर {percent}% है — आपने 80% सीमा पार कर ली। {skill} में आप विशेषज्ञ प्रमाणित हैं।", scoreRetry: "आपका स्कोर {percent}% है — 80% विशेषज्ञ सीमा से थोड़ा कम। फिर से प्रयास करें।",
    terminatedResult: "निगरानी के कारण यह प्रयास समाप्त कर दिया गया — {reason}। यह विशेषज्ञ दर्जे के लिए मान्य नहीं है।", tryAgain: "दूसरे कौशल का प्रयास करें"
  },
  Tamil: {
    easy: "எளிது", medium: "நடுத்தரம்", hard: "கடினம்", assessment: "தேர்வு", answered: "பதிலளிக்கப்பட்டது", generating: "உங்கள் {tier} கேள்விகள் உருவாக்கப்படுகின்றன…",
    gradingEasy: "எளிய நிலை மதிப்பிடப்படுகிறது, நடுத்தர கேள்விகள் உருவாக்கப்படுகின்றன…", gradingMedium: "நடுத்தர நிலை மதிப்பிடப்படுகிறது, கடின கேள்விகள் உருவாக்கப்படுகின்றன…",
    submitNext: "நிலையை சமர்ப்பித்து அடுத்ததைத் திறக்கவும்", submitResult: "சமர்ப்பித்து முடிவைப் பார்க்கவும்", answerEvery: "தொடர ஒவ்வொரு கேள்விக்கும் பதிலளிக்கவும்.",
    terminated: "தேர்வு நிறுத்தப்பட்டது", violation: "கண்காணிப்பில் விதிமீறல் கண்டறியப்பட்டதால் தேர்வு தானாக சமர்ப்பிக்கப்பட்டது. இந்த முயற்சி நிபுணர் நிலைக்கு தகுதியற்றது.",
    somethingWrong: "ஏதோ தவறு ஏற்பட்டது", backendHint: "Backend மற்றும் Ollama இயங்குகிறதா என்பதை உறுதி செய்யவும்.", back: "தொடக்கத்திற்குத் திரும்பு", stillWorking: "இன்னும் செயல்படுகிறது — உள்ளூர் மாடலுக்கு சிறிது நேரம் ஆகலாம்.",
    q: "கேள்வி", result: "தேர்வு முடிவு", correct: "சரி", points: "மதிப்பெண்", tierReview: "நிலை மதிப்பாய்வு", noAnswer: "பதில் இல்லை", youPicked: "நீங்கள் தேர்ந்தெடுத்தது", correctAnswer: "சரியான பதில்", expert: "நிபுணர்", disqualified: "தகுதியற்றது",
    scoreExpert: "உங்கள் மதிப்பெண் {percent}% — 80% வரம்பை கடந்துவிட்டீர்கள். {skill} இல் நீங்கள் நிபுணராக சான்றளிக்கப்பட்டுள்ளீர்கள்.", scoreRetry: "உங்கள் மதிப்பெண் {percent}% — 80% நிபுணர் வரம்பை விட சற்று குறைவு. மீண்டும் முயற்சிக்கவும்.",
    terminatedResult: "கண்காணிப்பு காரணமாக இந்த முயற்சி நிறுத்தப்பட்டது — {reason}. இது நிபுணர் நிலைக்கு தகுதியற்றது.", tryAgain: "வேறு திறனை முயற்சிக்கவும்"
  },
  Telugu: { easy:"సులభం",medium:"మధ్యస్థం",hard:"కష్టం",assessment:"పరీక్ష",answered:"సమాధానాలు",generating:"మీ {tier} ప్రశ్నలు రూపొందుతున్నాయి…",gradingEasy:"సులభ స్థాయిని పరిశీలిస్తున్నాం, మధ్యస్థ ప్రశ్నలు రూపొందుతున్నాయి…",gradingMedium:"మధ్యస్థ స్థాయిని పరిశీలిస్తున్నాం, కఠిన ప్రశ్నలు రూపొందుతున్నాయి…",submitNext:"స్థాయిని సమర్పించి తదుపరి స్థాయిని తెరవండి",submitResult:"సమర్పించి ఫలితాన్ని చూడండి",answerEvery:"కొనసాగించడానికి ప్రతి ప్రశ్నకు సమాధానం ఇవ్వండి.",terminated:"పరీక్ష ముగిసింది",violation:"పర్యవేక్షణలో నియమ ఉల్లంఘన గుర్తించబడింది. ఈ ప్రయత్నం నిపుణ స్థాయికి అర్హత లేదు.",somethingWrong:"ఏదో తప్పు జరిగింది",backendHint:"Backend మరియు Ollama నడుస్తున్నాయో చూడండి.",back:"ప్రారంభానికి తిరిగి వెళ్లండి",stillWorking:"ఇంకా పని జరుగుతోంది — స్థానిక మోడల్‌కు కొంత సమయం పట్టవచ్చు.",q:"ప్రశ్న",result:"పరీక్ష ఫలితం",correct:"సరి",points:"పాయింట్లు",tierReview:"స్థాయి సమీక్ష",noAnswer:"సమాధానం లేదు",youPicked:"మీరు ఎంచుకున్నది",correctAnswer:"సరైన సమాధానం",expert:"నిపుణుడు",disqualified:"అర్హత లేదు",scoreExpert:"మీ స్కోర్ {percent}% — 80% పరిమితిని దాటారు. {skill}లో మీరు నిపుణుడిగా ధృవీకరించబడ్డారు.",scoreRetry:"మీ స్కోర్ {percent}% — 80% నిపుణ పరిమితికి కొద్దిగా తక్కువ. మళ్లీ ప్రయత్నించండి.",terminatedResult:"పర్యవేక్షణ కారణంగా ప్రయత్నం ముగిసింది — {reason}.",tryAgain:"మరో నైపుణ్యాన్ని ప్రయత్నించండి"},
  Malayalam: { easy:"എളുപ്പം",medium:"മധ്യം",hard:"കഠിനം",assessment:"പരീക്ഷ",answered:"ഉത്തരം നൽകി",generating:"നിങ്ങളുടെ {tier} ചോദ്യങ്ങൾ തയ്യാറാക്കുന്നു…",gradingEasy:"എളുപ്പ നില പരിശോധിക്കുന്നു, മധ്യ ചോദ്യങ്ങൾ തയ്യാറാക്കുന്നു…",gradingMedium:"മധ്യ നില പരിശോധിക്കുന്നു, കഠിന ചോദ്യങ്ങൾ തയ്യാറാക്കുന്നു…",submitNext:"നില സമർപ്പിച്ച് അടുത്തത് തുറക്കുക",submitResult:"സമർപ്പിച്ച് ഫലം കാണുക",answerEvery:"തുടരാൻ എല്ലാ ചോദ്യങ്ങൾക്കും ഉത്തരം നൽകുക.",terminated:"പരീക്ഷ അവസാനിപ്പിച്ചു",violation:"പ്രോക്ടറിംഗ് നിയമലംഘനം കണ്ടെത്തി. ഈ ശ്രമം വിദഗ്ധ നിലയ്ക്ക് യോഗ്യമല്ല.",somethingWrong:"എന്തോ തെറ്റ് സംഭവിച്ചു",backendHint:"Backend, Ollama പ്രവർത്തിക്കുന്നുണ്ടെന്ന് ഉറപ്പാക്കുക.",back:"തുടക്കത്തിലേക്ക്",stillWorking:"ഇപ്പോഴും പ്രവർത്തിക്കുന്നു — പ്രാദേശിക മോഡലിന് കുറച്ച് സമയം എടുക്കാം.",q:"ചോദ്യം",result:"പരീക്ഷാ ഫലം",correct:"ശരി",points:"പോയിന്റ്",tierReview:"നില അവലോകനം",noAnswer:"ഉത്തരം ഇല്ല",youPicked:"നിങ്ങൾ തിരഞ്ഞെടുത്തത്",correctAnswer:"ശരിയായ ഉത്തരം",expert:"വിദഗ്ധൻ",disqualified:"അയോഗ്യം",scoreExpert:"നിങ്ങളുടെ സ്കോർ {percent}% — 80% പരിധി കടന്നു. {skill}ൽ നിങ്ങൾ വിദഗ്ധനായി സർട്ടിഫൈ ചെയ്തു.",scoreRetry:"നിങ്ങളുടെ സ്കോർ {percent}% — 80% വിദഗ്ധ പരിധിക്ക് കുറച്ച് താഴെ. വീണ്ടും ശ്രമിക്കുക.",terminatedResult:"പ്രോക്ടറിംഗ് കാരണം ശ്രമം അവസാനിപ്പിച്ചു — {reason}.",tryAgain:"മറ്റൊരു കഴിവ് ശ്രമിക്കുക"},
  Kannada: { easy:"ಸುಲಭ",medium:"ಮಧ್ಯಮ",hard:"ಕಠಿಣ",assessment:"ಪರೀಕ್ಷೆ",answered:"ಉತ್ತರಿಸಲಾಗಿದೆ",generating:"ನಿಮ್ಮ {tier} ಪ್ರಶ್ನೆಗಳು ರಚಿಸಲಾಗುತ್ತಿವೆ…",gradingEasy:"ಸುಲಭ ಹಂತ ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ, ಮಧ್ಯಮ ಪ್ರಶ್ನೆಗಳು ರಚಿಸಲಾಗುತ್ತಿವೆ…",gradingMedium:"ಮಧ್ಯಮ ಹಂತ ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ, ಕಠಿಣ ಪ್ರಶ್ನೆಗಳು ರಚಿಸಲಾಗುತ್ತಿವೆ…",submitNext:"ಹಂತ ಸಲ್ಲಿಸಿ ಮುಂದಿನದನ್ನು ತೆರೆಯಿರಿ",submitResult:"ಸಲ್ಲಿಸಿ ಫಲಿತಾಂಶ ನೋಡಿ",answerEvery:"ಮುಂದುವರಿಯಲು ಪ್ರತಿಯೊಂದು ಪ್ರಶ್ನೆಗೆ ಉತ್ತರಿಸಿ.",terminated:"ಪರೀಕ್ಷೆ ಮುಕ್ತಾಯಗೊಂಡಿದೆ",violation:"ಮೇಲ್ವಿಚಾರಣೆಯಲ್ಲಿ ನಿಯಮ ಉಲ್ಲಂಘನೆ ಕಂಡುಬಂದಿದೆ. ಈ ಪ್ರಯತ್ನ ತಜ್ಞ ಸ್ಥಾನಕ್ಕೆ ಅರ್ಹವಲ್ಲ.",somethingWrong:"ಏನೋ ತಪ್ಪಾಗಿದೆ",backendHint:"Backend ಮತ್ತು Ollama ಚಾಲನೆಯಲ್ಲಿವೆ ಎಂದು ಖಚಿತಪಡಿಸಿ.",back:"ಆರಂಭಕ್ಕೆ ಹಿಂತಿರುಗಿ",stillWorking:"ಇನ್ನೂ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತಿದೆ — ಸ್ಥಳೀಯ ಮಾದರಿಗೆ ಸ್ವಲ್ಪ ಸಮಯ ಬೇಕಾಗಬಹುದು.",q:"ಪ್ರಶ್ನೆ",result:"ಪರೀಕ್ಷಾ ಫಲಿತಾಂಶ",correct:"ಸರಿಯಾದ",points:"ಅಂಕಗಳು",tierReview:"ಹಂತ ಪರಿಶೀಲನೆ",noAnswer:"ಉತ್ತರ ಇಲ್ಲ",youPicked:"ನೀವು ಆಯ್ಕೆ ಮಾಡಿದದ್ದು",correctAnswer:"ಸರಿಯಾದ ಉತ್ತರ",expert:"ತಜ್ಞ",disqualified:"ಅರ್ಹವಲ್ಲ",scoreExpert:"ನಿಮ್ಮ ಸ್ಕೋರ್ {percent}% — 80% ಮಿತಿಯನ್ನು ದಾಟಿದ್ದೀರಿ. {skill}ನಲ್ಲಿ ನೀವು ತಜ್ಞರೆಂದು ಪ್ರಮಾಣೀಕರಿಸಲಾಗಿದೆ.",scoreRetry:"ನಿಮ್ಮ ಸ್ಕೋರ್ {percent}% — 80% ತಜ್ಞ ಮಿತಿಗಿಂತ ಸ್ವಲ್ಪ ಕಡಿಮೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",terminatedResult:"ಮೇಲ್ವಿಚಾರಣೆಯ ಕಾರಣ ಪ್ರಯತ್ನ ಮುಗಿದಿದೆ — {reason}.",tryAgain:"ಮತ್ತೊಂದು ಕೌಶಲ್ಯ ಪ್ರಯತ್ನಿಸಿ"},
  Spanish: { easy:"Fácil",medium:"Medio",hard:"Difícil",assessment:"Evaluación",answered:"respondidas",generating:"Generando tus preguntas de {tier}…",gradingEasy:"Evaluando Fácil y generando preguntas Medias…",gradingMedium:"Evaluando Medio y generando preguntas Difíciles…",submitNext:"Enviar nivel y desbloquear siguiente",submitResult:"Enviar y ver resultado",answerEvery:"Responde todas las preguntas para continuar.",terminated:"Evaluación terminada",violation:"La supervisión detectó una infracción. Este intento no puede obtener el nivel Experto.",somethingWrong:"Algo salió mal",backendHint:"Asegúrate de que el backend y Ollama estén ejecutándose.",back:"Volver al inicio",stillWorking:"Sigue trabajando — el modelo local puede tardar un poco.",q:"Pregunta",result:"Resultado",correct:"correctas",points:"puntos",tierReview:"revisión del nivel",noAnswer:"sin respuesta",youPicked:"Elegiste",correctAnswer:"Correcta",expert:"EXPERTO",disqualified:"DESCALIFICADO",scoreExpert:"Obtuviste {percent}% — superaste el 80%. Eres Experto certificado en {skill}.",scoreRetry:"Obtuviste {percent}% — justo por debajo del 80%. Inténtalo de nuevo.",terminatedResult:"El intento terminó por supervisión — {reason}.",tryAgain:"Probar otra habilidad"},
  French: { easy:"Facile",medium:"Moyen",hard:"Difficile",assessment:"Évaluation",answered:"répondues",generating:"Génération de vos questions {tier}…",gradingEasy:"Correction du niveau Facile et génération du niveau Moyen…",gradingMedium:"Correction du niveau Moyen et génération du niveau Difficile…",submitNext:"Soumettre et débloquer le niveau suivant",submitResult:"Soumettre et voir le résultat",answerEvery:"Répondez à toutes les questions pour continuer.",terminated:"Évaluation terminée",violation:"La surveillance a détecté une violation. Cette tentative n'est pas éligible au statut Expert.",somethingWrong:"Une erreur s'est produite",backendHint:"Vérifiez que le backend et Ollama sont actifs.",back:"Retour au début",stillWorking:"Traitement en cours — le modèle local peut prendre un peu de temps.",q:"Question",result:"Résultat",correct:"correctes",points:"points",tierReview:"révision",noAnswer:"aucune réponse",youPicked:"Votre choix",correctAnswer:"Correcte",expert:"EXPERT",disqualified:"DISQUALIFIÉ",scoreExpert:"Score {percent}% — seuil de 80% dépassé. Vous êtes Expert certifié en {skill}.",scoreRetry:"Score {percent}% — juste sous le seuil de 80%. Réessayez.",terminatedResult:"Tentative terminée par la surveillance — {reason}.",tryAgain:"Essayer une autre compétence"},
  German: { easy:"Leicht",medium:"Mittel",hard:"Schwer",assessment:"Prüfung",answered:"beantwortet",generating:"Deine {tier}-Fragen werden erstellt…",gradingEasy:"Leicht wird bewertet, Mittel-Fragen werden erstellt…",gradingMedium:"Mittel wird bewertet, Schwer-Fragen werden erstellt…",submitNext:"Stufe abgeben und nächste freischalten",submitResult:"Abgeben und Ergebnis anzeigen",answerEvery:"Beantworte alle Fragen, um fortzufahren.",terminated:"Prüfung beendet",violation:"Die Überwachung hat einen Regelverstoß erkannt. Dieser Versuch ist nicht für den Expertenstatus gültig.",somethingWrong:"Etwas ist schiefgelaufen",backendHint:"Stelle sicher, dass Backend und Ollama laufen.",back:"Zurück zum Start",stillWorking:"Wird noch verarbeitet — das lokale Modell kann etwas Zeit benötigen.",q:"Frage",result:"Prüfungsergebnis",correct:"richtig",points:"Punkte",tierReview:"Stufenprüfung",noAnswer:"keine Antwort",youPicked:"Deine Auswahl",correctAnswer:"Richtig",expert:"EXPERTE",disqualified:"DISQUALIFIZIERT",scoreExpert:"Du hast {percent}% erreicht — die 80%-Grenze ist überschritten. Du bist Experte für {skill}.",scoreRetry:"Du hast {percent}% erreicht — knapp unter 80%. Versuche es erneut.",terminatedResult:"Versuch durch Überwachung beendet — {reason}.",tryAgain:"Andere Fähigkeit versuchen"},
  Italian: { easy:"Facile",medium:"Medio",hard:"Difficile",assessment:"Valutazione",answered:"risposte",generating:"Generazione delle domande {tier}…",gradingEasy:"Valutazione Facile e generazione Medio…",gradingMedium:"Valutazione Medio e generazione Difficile…",submitNext:"Invia livello e sblocca il successivo",submitResult:"Invia e vedi risultato",answerEvery:"Rispondi a tutte le domande per continuare.",terminated:"Valutazione terminata",violation:"Il controllo ha rilevato una violazione. Il tentativo non è idoneo allo stato Esperto.",somethingWrong:"Qualcosa è andato storto",backendHint:"Assicurati che backend e Ollama siano attivi.",back:"Torna all'inizio",stillWorking:"Elaborazione in corso — il modello locale può richiedere tempo.",q:"Domanda",result:"Risultato",correct:"corrette",points:"punti",tierReview:"revisione",noAnswer:"nessuna risposta",youPicked:"Hai scelto",correctAnswer:"Corretta",expert:"ESPERTO",disqualified:"SQUALIFICATO",scoreExpert:"Hai ottenuto {percent}% — hai superato l'80%. Sei Esperto certificato in {skill}.",scoreRetry:"Hai ottenuto {percent}% — appena sotto l'80%. Riprova.",terminatedResult:"Tentativo terminato dal controllo — {reason}.",tryAgain:"Prova un'altra competenza"},
  Portuguese: { easy:"Fácil",medium:"Médio",hard:"Difícil",assessment:"Avaliação",answered:"respondidas",generating:"Gerando suas perguntas {tier}…",gradingEasy:"Avaliando Fácil e gerando Médio…",gradingMedium:"Avaliando Médio e gerando Difícil…",submitNext:"Enviar nível e desbloquear próximo",submitResult:"Enviar e ver resultado",answerEvery:"Responda todas as perguntas para continuar.",terminated:"Avaliação encerrada",violation:"A supervisão detectou uma violação. Esta tentativa não é elegível ao status Especialista.",somethingWrong:"Algo deu errado",backendHint:"Verifique se o backend e o Ollama estão em execução.",back:"Voltar ao início",stillWorking:"Ainda processando — o modelo local pode levar algum tempo.",q:"Pergunta",result:"Resultado",correct:"corretas",points:"pontos",tierReview:"revisão",noAnswer:"sem resposta",youPicked:"Você escolheu",correctAnswer:"Correta",expert:"ESPECIALISTA",disqualified:"DESQUALIFICADO",scoreExpert:"Você marcou {percent}% — acima de 80%. Você é Especialista certificado em {skill}.",scoreRetry:"Você marcou {percent}% — pouco abaixo de 80%. Tente novamente.",terminatedResult:"Tentativa encerrada pela supervisão — {reason}.",tryAgain:"Tentar outra habilidade"},
  Russian: { easy:"Легко",medium:"Средне",hard:"Сложно",assessment:"Экзамен",answered:"отвечено",generating:"Создаются вопросы уровня {tier}…",gradingEasy:"Проверяем лёгкий уровень и создаём средние вопросы…",gradingMedium:"Проверяем средний уровень и создаём сложные вопросы…",submitNext:"Отправить и открыть следующий уровень",submitResult:"Отправить и увидеть результат",answerEvery:"Ответьте на все вопросы, чтобы продолжить.",terminated:"Экзамен завершён",violation:"Система контроля обнаружила нарушение. Попытка не может получить статус эксперта.",somethingWrong:"Что-то пошло не так",backendHint:"Убедитесь, что backend и Ollama запущены.",back:"Назад",stillWorking:"Обработка продолжается — локальной модели может потребоваться время.",q:"Вопрос",result:"Результат",correct:"верно",points:"баллов",tierReview:"проверка уровня",noAnswer:"нет ответа",youPicked:"Вы выбрали",correctAnswer:"Верно",expert:"ЭКСПЕРТ",disqualified:"ДИСКВАЛИФИЦИРОВАН",scoreExpert:"Ваш результат {percent}% — выше порога 80%. Вы сертифицированный эксперт по {skill}.",scoreRetry:"Ваш результат {percent}% — немного ниже 80%. Попробуйте снова.",terminatedResult:"Попытка завершена контролем — {reason}.",tryAgain:"Попробовать другой навык"},
  Arabic: { easy:"سهل",medium:"متوسط",hard:"صعب",assessment:"اختبار",answered:"تمت الإجابة",generating:"جارٍ إنشاء أسئلة المستوى {tier}…",gradingEasy:"جارٍ تصحيح السهل وإنشاء أسئلة المتوسط…",gradingMedium:"جارٍ تصحيح المتوسط وإنشاء أسئلة الصعب…",submitNext:"إرسال المستوى وفتح التالي",submitResult:"إرسال ورؤية النتيجة",answerEvery:"أجب عن جميع الأسئلة للمتابعة.",terminated:"تم إنهاء الاختبار",violation:"اكتشف نظام المراقبة مخالفة. هذه المحاولة غير مؤهلة لحالة الخبير.",somethingWrong:"حدث خطأ",backendHint:"تأكد من تشغيل الخادم وOllama.",back:"العودة للبداية",stillWorking:"لا يزال قيد المعالجة — قد يحتاج النموذج المحلي إلى بعض الوقت.",q:"سؤال",result:"نتيجة الاختبار",correct:"صحيح",points:"نقاط",tierReview:"مراجعة المستوى",noAnswer:"لا توجد إجابة",youPicked:"اخترت",correctAnswer:"الصحيح",expert:"خبير",disqualified:"غير مؤهل",scoreExpert:"نتيجتك {percent}% — تجاوزت حد 80%. أنت خبير معتمد في {skill}.",scoreRetry:"نتيجتك {percent}% — أقل قليلًا من حد 80%. حاول مرة أخرى.",terminatedResult:"تم إنهاء المحاولة بسبب المراقبة — {reason}.",tryAgain:"جرّب مهارة أخرى"},
  Japanese: { easy:"初級",medium:"中級",hard:"上級",assessment:"試験",answered:"回答済み",generating:"{tier}問題を生成しています…",gradingEasy:"初級を採点し、中級問題を生成しています…",gradingMedium:"中級を採点し、上級問題を生成しています…",submitNext:"提出して次のレベルを開く",submitResult:"提出して結果を見る",answerEvery:"続行するにはすべての問題に回答してください。",terminated:"試験終了",violation:"監視システムが違反を検出しました。この受験はExpert資格の対象外です。",somethingWrong:"問題が発生しました",backendHint:"バックエンドとOllamaが起動していることを確認してください。",back:"開始に戻る",stillWorking:"処理中です — ローカルモデルには時間がかかる場合があります。",q:"問題",result:"試験結果",correct:"正解",points:"点",tierReview:"レベル確認",noAnswer:"未回答",youPicked:"選択",correctAnswer:"正解",expert:"EXPERT",disqualified:"失格",scoreExpert:"スコアは{percent}% — 80%を超えました。{skill}のExpertとして認定されました。",scoreRetry:"スコアは{percent}% — 80%を少し下回っています。もう一度お試しください。",terminatedResult:"監視により受験が終了しました — {reason}。",tryAgain:"別のスキルを試す"},
  Korean: { easy:"쉬움",medium:"보통",hard:"어려움",assessment:"시험",answered:"답변 완료",generating:"{tier} 문제를 생성하는 중…",gradingEasy:"쉬움 채점 및 보통 문제 생성 중…",gradingMedium:"보통 채점 및 어려움 문제 생성 중…",submitNext:"제출하고 다음 단계 열기",submitResult:"제출하고 결과 보기",answerEvery:"계속하려면 모든 문제에 답하세요.",terminated:"시험 종료",violation:"감독 시스템에서 규칙 위반을 감지했습니다. 이 시도는 전문가 자격 대상이 아닙니다.",somethingWrong:"문제가 발생했습니다",backendHint:"백엔드와 Ollama가 실행 중인지 확인하세요.",back:"처음으로",stillWorking:"처리 중입니다 — 로컬 모델은 시간이 걸릴 수 있습니다.",q:"문제",result:"시험 결과",correct:"정답",points:"점",tierReview:"단계 검토",noAnswer:"미응답",youPicked:"선택",correctAnswer:"정답",expert:"전문가",disqualified:"실격",scoreExpert:"점수 {percent}% — 80%를 넘었습니다. {skill} 전문가로 인증되었습니다.",scoreRetry:"점수 {percent}% — 80%보다 조금 낮습니다. 다시 시도하세요.",terminatedResult:"감독으로 인해 시도가 종료되었습니다 — {reason}.",tryAgain:"다른 기술 시도"},
  Chinese: { easy:"简单",medium:"中等",hard:"困难",assessment:"考试",answered:"已回答",generating:"正在生成{tier}问题…",gradingEasy:"正在批改简单题并生成中等题…",gradingMedium:"正在批改中等题并生成困难题…",submitNext:"提交并解锁下一阶段",submitResult:"提交并查看结果",answerEvery:"请回答所有问题后继续。",terminated:"考试已结束",violation:"监考系统检测到违规。此次考试不具备专家资格。",somethingWrong:"发生错误",backendHint:"请确认后端和 Ollama 正在运行。",back:"返回开始",stillWorking:"仍在处理 — 本地模型可能需要一些时间。",q:"问题",result:"考试结果",correct:"正确",points:"分",tierReview:"阶段复核",noAnswer:"未回答",youPicked:"你的选择",correctAnswer:"正确答案",expert:"专家",disqualified:"不合格",scoreExpert:"你的得分为 {percent}% — 已超过80%门槛。你已获得{skill}专家认证。",scoreRetry:"你的得分为 {percent}% — 略低于80%。请再次尝试。",terminatedResult:"监考导致此次考试结束 — {reason}。",tryAgain:"尝试其他技能"},
  Bengali: { easy:"সহজ",medium:"মাঝারি",hard:"কঠিন",assessment:"পরীক্ষা",answered:"উত্তর দেওয়া",generating:"আপনার {tier} প্রশ্ন তৈরি হচ্ছে…",gradingEasy:"সহজ স্তর যাচাই হচ্ছে, মাঝারি প্রশ্ন তৈরি হচ্ছে…",gradingMedium:"মাঝারি স্তর যাচাই হচ্ছে, কঠিন প্রশ্ন তৈরি হচ্ছে…",submitNext:"স্তর জমা দিন এবং পরেরটি খুলুন",submitResult:"জমা দিন ও ফলাফল দেখুন",answerEvery:"চালিয়ে যেতে সব প্রশ্নের উত্তর দিন।",terminated:"পরীক্ষা শেষ",violation:"নজরদারিতে নিয়ম ভঙ্গ শনাক্ত হয়েছে। এই প্রচেষ্টা বিশেষজ্ঞ মর্যাদার জন্য যোগ্য নয়।",somethingWrong:"কিছু ভুল হয়েছে",backendHint:"Backend ও Ollama চালু আছে কিনা নিশ্চিত করুন।",back:"শুরুতে ফিরুন",stillWorking:"এখনও কাজ চলছে — স্থানীয় মডেলের কিছু সময় লাগতে পারে।",q:"প্রশ্ন",result:"পরীক্ষার ফলাফল",correct:"সঠিক",points:"পয়েন্ট",tierReview:"স্তর পর্যালোচনা",noAnswer:"কোনো উত্তর নেই",youPicked:"আপনি বেছে নিয়েছেন",correctAnswer:"সঠিক উত্তর",expert:"বিশেষজ্ঞ",disqualified:"অযোগ্য",scoreExpert:"আপনার স্কোর {percent}% — ৮০% সীমা পেরিয়েছেন। {skill}-এ আপনি বিশেষজ্ঞ হিসেবে স্বীকৃত।",scoreRetry:"আপনার স্কোর {percent}% — ৮০% সীমার একটু নিচে। আবার চেষ্টা করুন।",terminatedResult:"নজরদারির কারণে প্রচেষ্টা শেষ হয়েছে — {reason}।",tryAgain:"অন্য দক্ষতা চেষ্টা করুন"},
  Marathi: { easy:"सोपे",medium:"मध्यम",hard:"कठीण",assessment:"परीक्षा",answered:"उत्तरे दिली",generating:"तुमचे {tier} प्रश्न तयार होत आहेत…",gradingEasy:"सोप्या स्तराचे मूल्यमापन आणि मध्यम प्रश्न तयार होत आहेत…",gradingMedium:"मध्यम स्तराचे मूल्यमापन आणि कठीण प्रश्न तयार होत आहेत…",submitNext:"स्तर सबमिट करा आणि पुढील उघडा",submitResult:"सबमिट करा आणि निकाल पहा",answerEvery:"पुढे जाण्यासाठी प्रत्येक प्रश्नाचे उत्तर द्या.",terminated:"परीक्षा समाप्त",violation:"निगराणीमध्ये नियमभंग आढळला. हा प्रयत्न तज्ञ दर्जासाठी पात्र नाही.",somethingWrong:"काहीतरी चूक झाली",backendHint:"Backend आणि Ollama चालू आहेत याची खात्री करा.",back:"सुरुवातीला परत जा",stillWorking:"अजून प्रक्रिया सुरू आहे — स्थानिक मॉडेलला वेळ लागू शकतो.",q:"प्रश्न",result:"परीक्षा निकाल",correct:"बरोबर",points:"गुण",tierReview:"स्तर पुनरावलोकन",noAnswer:"उत्तर नाही",youPicked:"तुमची निवड",correctAnswer:"योग्य उत्तर",expert:"तज्ञ",disqualified:"अपात्र",scoreExpert:"तुमचा स्कोअर {percent}% — ८०% मर्यादा पार केली. {skill} मध्ये तुम्ही प्रमाणित तज्ञ आहात.",scoreRetry:"तुमचा स्कोअर {percent}% — ८०% पेक्षा थोडा कमी. पुन्हा प्रयत्न करा.",terminatedResult:"निगराणीमुळे प्रयत्न समाप्त — {reason}.",tryAgain:"दुसरे कौशल्य वापरा"},
  Gujarati: { easy:"સરળ",medium:"મધ્યમ",hard:"કઠિન",assessment:"પરીક્ષા",answered:"જવાબ આપ્યા",generating:"તમારા {tier} પ્રશ્નો તૈયાર થઈ રહ્યા છે…",gradingEasy:"સરળ સ્તર ચકાસી રહ્યા છીએ, મધ્યમ પ્રશ્નો તૈયાર થઈ રહ્યા છે…",gradingMedium:"મધ્યમ સ્તર ચકાસી રહ્યા છીએ, કઠિન પ્રશ્નો તૈયાર થઈ રહ્યા છે…",submitNext:"સ્તર સબમિટ કરો અને આગળનું ખોલો",submitResult:"સબમિટ કરો અને પરિણામ જુઓ",answerEvery:"આગળ વધવા માટે દરેક પ્રશ્નનો જવાબ આપો.",terminated:"પરીક્ષા સમાપ્ત",violation:"નિરીક્ષણમાં નિયમભંગ મળ્યો. આ પ્રયાસ નિષ્ણાત દરજ્જા માટે યોગ્ય નથી.",somethingWrong:"કંઈક ખોટું થયું",backendHint:"Backend અને Ollama ચાલુ છે તેની ખાતરી કરો.",back:"શરૂઆત પર પાછા જાઓ",stillWorking:"હજી પ્રક્રિયા ચાલી રહી છે — સ્થાનિક મોડલને સમય લાગી શકે છે.",q:"પ્રશ્ન",result:"પરીક્ષાનું પરિણામ",correct:"સાચું",points:"ગુણ",tierReview:"સ્તર સમીક્ષા",noAnswer:"જવાબ નથી",youPicked:"તમારી પસંદગી",correctAnswer:"સાચો જવાબ",expert:"નિષ્ણાત",disqualified:"અયોગ્ય",scoreExpert:"તમારો સ્કોર {percent}% — 80% મર્યાદા પાર કરી. {skill}માં તમે પ્રમાણિત નિષ્ણાત છો.",scoreRetry:"તમારો સ્કોર {percent}% — 80%થી થોડો ઓછો. ફરી પ્રયાસ કરો.",terminatedResult:"નિરીક્ષણને કારણે પ્રયાસ સમાપ્ત — {reason}.",tryAgain:"બીજું કૌશલ્ય અજમાવો"},
  Punjabi: { easy:"ਆਸਾਨ",medium:"ਮੱਧਮ",hard:"ਔਖਾ",assessment:"ਪਰੀਖਿਆ",answered:"ਜਵਾਬ ਦਿੱਤੇ",generating:"ਤੁਹਾਡੇ {tier} ਸਵਾਲ ਬਣਾਏ ਜਾ ਰਹੇ ਹਨ…",gradingEasy:"ਆਸਾਨ ਪੱਧਰ ਦੀ ਜਾਂਚ ਅਤੇ ਮੱਧਮ ਸਵਾਲ ਤਿਆਰ ਹੋ ਰਹੇ ਹਨ…",gradingMedium:"ਮੱਧਮ ਪੱਧਰ ਦੀ ਜਾਂਚ ਅਤੇ ਔਖੇ ਸਵਾਲ ਤਿਆਰ ਹੋ ਰਹੇ ਹਨ…",submitNext:"ਪੱਧਰ ਜਮ੍ਹਾਂ ਕਰੋ ਅਤੇ ਅਗਲਾ ਖੋਲ੍ਹੋ",submitResult:"ਜਮ੍ਹਾਂ ਕਰੋ ਅਤੇ ਨਤੀਜਾ ਵੇਖੋ",answerEvery:"ਜਾਰੀ ਰੱਖਣ ਲਈ ਹਰ ਸਵਾਲ ਦਾ ਜਵਾਬ ਦਿਓ।",terminated:"ਪਰੀਖਿਆ ਸਮਾਪਤ",violation:"ਨਿਗਰਾਨੀ ਵਿੱਚ ਨਿਯਮ ਦੀ ਉਲੰਘਣਾ ਮਿਲੀ। ਇਹ ਕੋਸ਼ਿਸ਼ ਮਾਹਰ ਦਰਜੇ ਲਈ ਯੋਗ ਨਹੀਂ ਹੈ।",somethingWrong:"ਕੁਝ ਗਲਤ ਹੋਇਆ",backendHint:"Backend ਅਤੇ Ollama ਚੱਲ ਰਹੇ ਹਨ ਇਹ ਯਕੀਨੀ ਬਣਾਓ।",back:"ਸ਼ੁਰੂਆਤ ਵੱਲ ਵਾਪਸ",stillWorking:"ਹਾਲੇ ਕੰਮ ਚੱਲ ਰਿਹਾ ਹੈ — ਸਥਾਨਕ ਮਾਡਲ ਨੂੰ ਸਮਾਂ ਲੱਗ ਸਕਦਾ ਹੈ।",q:"ਸਵਾਲ",result:"ਪਰੀਖਿਆ ਨਤੀਜਾ",correct:"ਸਹੀ",points:"ਅੰਕ",tierReview:"ਪੱਧਰ ਸਮੀਖਿਆ",noAnswer:"ਕੋਈ ਜਵਾਬ ਨਹੀਂ",youPicked:"ਤੁਸੀਂ ਚੁਣਿਆ",correctAnswer:"ਸਹੀ ਜਵਾਬ",expert:"ਮਾਹਰ",disqualified:"ਅਯੋਗ",scoreExpert:"ਤੁਹਾਡਾ ਸਕੋਰ {percent}% — 80% ਸੀਮਾ ਪਾਰ। {skill} ਵਿੱਚ ਤੁਸੀਂ ਪ੍ਰਮਾਣਿਤ ਮਾਹਰ ਹੋ।",scoreRetry:"ਤੁਹਾਡਾ ਸਕੋਰ {percent}% — 80% ਤੋਂ ਥੋੜ੍ਹਾ ਘੱਟ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",terminatedResult:"ਨਿਗਰਾਨੀ ਕਾਰਨ ਕੋਸ਼ਿਸ਼ ਸਮਾਪਤ — {reason}।",tryAgain:"ਹੋਰ ਹੁਨਰ ਅਜ਼ਮਾਓ"},
  Urdu: { easy:"آسان",medium:"درمیانہ",hard:"مشکل",assessment:"امتحان",answered:"جواب دیے گئے",generating:"آپ کے {tier} سوالات تیار ہو رہے ہیں…",gradingEasy:"آسان مرحلہ چیک ہو رہا ہے، درمیانے سوالات تیار ہو رہے ہیں…",gradingMedium:"درمیانہ مرحلہ چیک ہو رہا ہے، مشکل سوالات تیار ہو رہے ہیں…",submitNext:"مرحلہ جمع کریں اور اگلا کھولیں",submitResult:"جمع کریں اور نتیجہ دیکھیں",answerEvery:"جاری رکھنے کے لیے ہر سوال کا جواب دیں۔",terminated:"امتحان ختم",violation:"نگرانی میں اصول کی خلاف ورزی ملی۔ یہ کوشش ماہر درجہ کے لیے اہل نہیں۔",somethingWrong:"کچھ غلط ہو گیا",backendHint:"یقینی بنائیں کہ Backend اور Ollama چل رہے ہیں۔",back:"شروع پر واپس جائیں",stillWorking:"ابھی کام جاری ہے — مقامی ماڈل کو کچھ وقت لگ سکتا ہے۔",q:"سوال",result:"امتحان کا نتیجہ",correct:"درست",points:"نمبر",tierReview:"مرحلہ جائزہ",noAnswer:"کوئی جواب نہیں",youPicked:"آپ نے منتخب کیا",correctAnswer:"درست جواب",expert:"ماہر",disqualified:"نااہل",scoreExpert:"آپ کا اسکور {percent}% ہے — 80% حد عبور کر لی۔ آپ {skill} میں ماہر تصدیق شدہ ہیں۔",scoreRetry:"آپ کا اسکور {percent}% ہے — 80% سے تھوڑا کم۔ دوبارہ کوشش کریں۔",terminatedResult:"نگرانی کی وجہ سے کوشش ختم — {reason}۔",tryAgain:"دوسری مہارت آزمائیں"}
};

export function getUI(language = "English") {
  return UI[language] || UI.English;
}
